apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - name: tcp-80
    port: 10080
    protocol: TCP
    targetPort: 80
    appProtocol: http
  selector:
    run: my-nginx
