apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-read
  namespace: default
rules:
- apiGroups: [""]
  resourceNames: []
  resources: ["pods"]
  verbs: ["get","watch","list"]
