apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-deployment
  namespace: default
rules:
- apiGroups: ["apps/v1"]
  resourceNames: []
  resources: ["deployments"]
  verbs: ["get","watch","list","create","update","patch","delete"]
