apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-read-bind
roleRef:
  kind: Role
  name: role-read
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: test
