---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: dev
  labels:
    app: myweb
spec:
  containers:
  - name: myweb
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: test-pod
  namespace: dev
  labels:
    app: myweb
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30880
  selector:
    app: myweb
