apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zhangsan-role
  namespace: dev
rules:
- apiGroups: ["","apps"]
  resources: ["deployments", "replicasets", "pods", "services"]
  verbs: ["*"]
