apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node02
  containers:
  - name: nginx
    image: nginx:latest
  tolerations:
    - key: "node-type"
      operator: "Exists"
      effect: ""
