apiVersion: v1
kind: Pod
metadata:
  name: gateway
  namespace: default
  labels:
    app: gateway
spec:
  initContainers:
  - name: init-check-harbor
    image: rancher/curl:latest
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', "until curl -I http://192.168.128.11:80; do sleep 2; echo 'please wait...'; sleep 3; done;"]
  containers:
  - name: gateway
    image: nginx:latest
    imagePullPolicy: IfNotPresent
