apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  initContainers:
  - name: install
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command:
    - wget
    - "-O"
    - "/work/index.html"
    - "https://www.baidu.com"
    volumeMounts:
    - name: work
      mountPath: /work
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: work
      mountPath: /usr/share/nginx/html
  volumes:
  - name: work
    emptyDir: {}
