apiVersion: v1
kind: Pod
metadata:
  name: nginx-web
  namespace: default
  labels:
    app: web
spec:
  containers:
  - name: nginx-web
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command:
          - "/bin/sh"
          - "-c"
          - "echo 'hello hook' > /usr/share/nginx/html/index.html"
      preStop:
        exec:
          command:
          - "/bin/sh"
          - "-c"
          - "nginx -s stop"
