apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  namespace: default
  labels:
    app: liveness-exec
spec:
  containers:
  - name: liveness-exec
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 10; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      initialDelaySeconds: 20
      periodSeconds: 10
      failureThreshold: 2
      exec:
        command:
        - cat
        - /tmp/healthy
