apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp
  namespace: default
  labels:
    app: liveness-tcp
spec:
  containers:
  - name: liveness-tcp
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      initialDelaySeconds: 20
      periodSeconds: 10
      failureThreshold: 2
      tcpSocket:
        port: 80
