apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
  namespace: default
  labels:
    app: liveness-http
spec:
  containers:
  - name: liveness-http
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      initialDelaySeconds: 20
      periodSeconds: 10
      failureThreshold: 2
      httpGet:
        scheme: HTTP
        port: 80
        path: /index.html
