apiVersion: v1
kind: Pod
metadata:
  name: readiness-http
  namespace: default
  labels:
    app: readiness-http
spec:
  containers:
  - name: readiness-http
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
    readinessProbe:
      initialDelaySeconds: 20
      periodSeconds: 10
      failureThreshold: 2
      httpGet:
        scheme: HTTP
        port: 80
        path: /index.html
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-http
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: readiness-http
