apiVersion: v1
kind: Pod
metadata:
  name: readiness-tcp
  namespace: default
  labels:
    app: readiness-tcp
spec:
  containers:
  - name: readiness-tcp
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
    readinessProbe:
      initialDelaySeconds: 20
      periodSeconds: 10
      failureThreshold: 2
      tcpSocket:
        port: 80
