apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: default
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
    startupProbe:
      exec:
        command:
        - sh
        - -c 
        - curl -I 192.168.128.11
    livenessProbe:
      initialDelaySeconds: 20
      periodSeconds: 10
      failureThreshold: 2
      tcpSocket:
        port: 80
    readinessProbe:
      initialDelaySeconds: 20
      periodSeconds: 10
      failureThreshold: 2
      tcpSocket:
        port: 80
