apiVersion: v1
kind: Pod
metadata:
  name: nginx-high
  namespace: default
spec:
  nodeSelector: 
    kubernetes.io/hostname: k8s-node01
  priorityClassName: high
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - web
        topologyKey: kubernetes.io/hostname
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
