apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  namespace: default
  labels:
    app: tomcat
    web: v1
spec:
  containers:
  - name: tomcat
    ports:
    - containerPort: 8080
    image: tomcat
    imagePullPolicy: IfNotPresent
