apiVersion: v1
kind: Pod
metadata:
  name: pod-node-affinity-apache
  namespace: default
  labels:
    app: apache
    web: https
spec:
  containers:
  - name: apache
    image: httpd:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: web
              operator: In
              values:
              - http
              - https
