apiVersion: v1
kind: Pod
metadata:
  name: pod-node-affinity-nginx
  namespace: default
  labels:
    app: nginx
    web: https
spec:
  containers:
  - name: nginx
    image: nginx:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - {key: zone, operator: Exists, values: []}
