apiVersion: v1
kind: Pod
metadata:
  name: resource-nginx
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - name: web
      containerPort: 80
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "1024Mi"
        cpu: "100m"
      limits:
        memory: "2048Mi"
        cpu: "500m"
