apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: default
  labels:
    name: static-web
spec:
  containers:
  - name: static-web
    image: nginx:latest
    ports:
    - name: web
      containerPort: 80
