apiVersion: v1
kind: Pod
metadata:
  name: cm-appvars-pod
spec:
  containers:
  - name: cm-appvars-pod
    image: nginx:latest
    env:
    - name: APPDATADIR
      valueFrom:
        configMapKeyRef:
          name: cm-appvars
          key: appdatadir
    - name: APPLOGLEVEL
      valueFrom:
        configMapKeyRef:
          name: cm-appvars
          key: apploglevel
