apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-volume
spec:
  containers:
  - name: mysql
    image: nginx:latest
    command: [ "/bin/sh","-c","sleep 3600" ]
    volumeMounts:
    - name: mysql-config
      mountPath: /etc/nginx/my.cnf
      subPath: my-test.cnf
  volumes:
  - name: mysql-config
    configMap:
      name: mysql
      items:
      - key: my.cnf
        path: my-test.cnf
  restartPolicy: Never
