---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-cert-exporter
  namespace: monitor
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-cert-exporter
  name: node-cert-exporter
  namespace: monitor
spec:
  selector:
    matchLabels:
      app: node-cert-exporter
  template:
    metadata:
      name: node-cert-exporter
      labels:
        app: node-cert-exporter
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
      - name: node-cert-exporter
        image: amimof/node-cert-exporter:latest
        args:
        - "--v=2"
        - "--logtostderr=true"
        - "--path=/host/etc/ssl,/host/etc/kubernetes/pki/,/host/etc/kubernetes/ssl"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        ports:
        - containerPort: 9117
          name: http
          protocol: TCP
#        resources:
#          limits:
#            cpu: 500m
#            memory: 500Mi
#          requests:
#            cpu: 50m
#            memory: 50Mi
        volumeMounts:
        - name: etc
          mountPath: /host/etc
          readOnly: true
      serviceAccount: node-cert-exporter
      serviceAccountName: node-cert-exporter
      volumes:
      - name: etc
        hostPath:
          path: /etc
          type: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
  updateStrategy:
    type: RollingUpdate
