apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: monitor
spec:
  selector:
    app: pushgateway
  type: NodePort
  ports:
  - name: tcp-9091
    port: 9091
    targetPort: 9091
    protocol: TCP
    nodePort: 30091
