apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  namespace: devops
  labels:
    app: tomcat-pod-test
spec:
  containers:
  - name:  tomcat-test
    ports:
    - containerPort: 8080
    image: tomcat
    resources:
        limits:
          memory: "2Gi"
          cpu: "1"
        requests:
          memory: "500Mi"
          cpu: "500m"
