kind: ConfigMap
apiVersion: v1
metadata:
  name: deploy-group1
data:
  index.html: |-
    Welcome to the deploy-group1 test page
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-group1
spec:
  replicas: 10
  selector:
   matchLabels:
    app: web
  template:
   metadata:
    labels:
     app: web
   spec:
    containers:
    - name: web
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: index-html
        mountPath: /usr/share/nginx/html/index.html
        subPath: index.html
    volumes:
      - name: index-html
        configMap:
          name: deploy-group1
          items:
          - key: index.html
            path: index.html
