apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
  - name: hostpath
    image: nginx
    volumeMounts:
    - name: test-volume
      mountPath: /test-nginx
  volumes:
  - name: test-volume
    hostPath:
      path: /data1
      type: DirectoryOrCreate
