apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/lfy_k8s_images/nfs-subdir-external-provisioner:v4.0.2
          # resources:
          #    limits:
          #      cpu: 10m
          #    requests:
          #      cpu: 10m
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME  #供应商名称，创建SC的时候需要指定
              value: kubernetes.test/nfs
            - name: NFS_SERVER  #指定nfs服务器地址
              value: 192.168.128.11
            - name: NFS_PATH  #指定nfs服务器共享的目录
              value: /nfs/data
      volumes:
        - name: nfs-client-root
          nfs:   #使用nfs方式进行挂载，挂载到容器内
            server: 192.168.128.11
            path: /nfs/data
