apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
spec:
  containers:
  - name: nfs-test
    image: nginx
    volumeMounts:
      - name: nfs-pvc
        mountPath: /usr/share/nginx/html
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: nfs-test-pvc
