apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-configmap
  namespace: monitor
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: dingding
    receivers:
    - name: 'dingding'
      webhook_configs:
      - url: 'http://192.168.128.11:8060/dingtalk/kubernetes/send'
        send_resolved: true
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']
