apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitor
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - name: tcp-3000
    port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 30300
