apiVersion: v1
kind: Pod
metadata:
  name: myapp-2
spec:
  containers:
    - name: myapp-2
      image: nginx:latest
      env:
        - name: mysql_username
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: mysql_password
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
