apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-2
spec:
  containers:
    - name: mycontainer
      image: nginx:latest
      volumeMounts:
        - name: mysecret-volume
          mountPath: /etc/mysecret
          readOnly: true
  volumes:
    - name: mysecret-volume
      secret:
        secretName: mysql-user-pass
