apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx-ssl.conf: |
    server {
        listen 443 ssl;
        server_name localhost;
    
        ssl_certificate /etc/tls/tls.crt;
        ssl_certificate_key /etc/tls/tls.key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
        ssl_prefer_server_ciphers on;
      
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
    }
