apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitor
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - name: tcp-9090
    port: 9090
    targetPort: 9090
    protocol: TCP
    nodePort: 30090
